eureka:
  instance:
    prefer-ip-address: true
    hostname: recruit-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka