eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/gateway/user/**
          filters:
            - RewritePath=/gateway/user/(?<segment>.*), /${segment}

        - id: club
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/gateway/club/**
          filters:
            - RewritePath=/gateway/club/(?<segment>.*), /${segment}

        - id: place
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/gateway/place/**
          filters:
            - RewritePath=/gateway/place/(?<segment>.*), /${segment}

        - id: recruit
          uri: lb://RECRUIT-SERVICE
          predicates:
            - Path=/gateway/recruit/**
          filters:
            - RewritePath=/gateway/recruit/(?<segment>.*), /${segment}