server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user
            uri: http://localhost:8091
            predicates:
              - Path=/user/**
          - id: recruit
            uri: http://localhost:8092
            predicates:
              - Path=/recruit/**
          - id: club
            uri: http://localhost:8093
            predicates:
              - Path=/club/**
          - id: place
            uri: http://localhost:8094
            predicates:
              - Path=/place/**