name: CI club-service

# main 브랜치 push & club-service의 변경 내역이 있는 경우
on:
  push:
    branches: [ "main" ]
    paths:
      - 'club/**'

env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}                                 # Helm Chart GitHub Target Repository Token
  TARGET_REPOSITORY: ${{ vars.TARGET_REPOSITORY }}                    # Helm Chart Github Path
  SEQUENCE_NUMBER: ${{ github.run_number }}                           # workflow Sequence Number, Use Docker Image Tag
  DOCKER_HUB_REGISTRY_NAME: ${{ secrets.DOCKER_HUB_REGISTRY_NAME }}   # Docker Hub Registry Name
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}                     # Docker Hub Username
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}                     # Docker Hub Password
  CI_REGISTRY: ${{ vars.CI_REGISTRY }}                                # CI Registry

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Build with Gradle 8.8
        run: |
          cd club
          gradle clean build --exclude-task test

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login --password-stdin -u "${{ env.DOCKER_USERNAME }}" -- ${{ env.CI_REGISTRY }}

      - name: Build Docker Image
        run: |
          cd club
          docker build -t gigboard-club .
          docker tag gigboard-club ${{ env.DOCKER_HUB_REGISTRY_NAME }}/gigboard-club:${{ env.SEQUENCE_NUMBER }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_REGISTRY_NAME }}/gigboard-club:${{ env.SEQUENCE_NUMBER }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ env.GIT_TOKEN }}
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'values.yaml'
          value: ${{ env.SEQUENCE_NUMBER }}
          propertyPath: 'clubDeployment.gigboardClub.image.tag'
          message: 'CI: Update Club Image Tag to ${{ env.SEQUENCE_NUMBER }}'
          commitChange: true
          branch: main
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ env.GIT_TOKEN }}